### ISSUE TITLE
errors in console with custom-component

### ISSUE THREAD

**Issue by Paul75** [pavvank/tb-carousel#1] opened 2019-02-12 09:05 UTC
Hello,

I have error with custom component. See : https://stackblitz.com/edit/tb-carousel-demo

Thanks

**Comment by pavvank** [comment] 2019-02-12 12:09
Hi, I am looking at the issue will respond as soon as possible.

**Comment by pavvank** [comment] 2019-02-12 13:56
Try giving values of card height and width in pixels or any other unit other than %. The issue is everything is in %.

**Comment by Paul75** [comment] 2019-02-12 13:58
oh for me I must do carousel with fullscreen ....

**Comment by Paul75** [comment] 2019-02-12 13:59
the error in exemple is : 

ERROR
Error: Cannot read property 'heading' of undefined

**Comment by pavvank** [comment] 2019-02-12 14:04
For full screen try using vh a vw for full screen

**Comment by pavvank** [comment] 2019-02-12 15:16
try renaming modelObject to  _tbModelObject in CarouselComponent class. and respectively in its html.
*need to update readme.md. Working on addition of more kind of carousels. Will be up by end of this week.

**Comment by pavvank** [comment] 2019-02-12 15:20
Tell me if your issue is resolved

**Comment by Paul75** [comment] 2019-02-12 15:23
it seem resolved

**Comment by pavvank** [comment] 2019-02-12 15:26
Alright. :)

**Comment by Paul75** [comment] 2019-02-12 16:12
for see, I do this but when I can modiify CSS ? because I add 100vh and 100vw but now I see scrools and it take more for all the screen ....

**Comment by pavvank** [comment] 2019-02-12 16:19
Use 
  cardHeight="80vh"
  cardWidth="90vw" 

and remove   
  containerWidth="100vh"
  containerHeight="100vh"

In next update sizing will be fixed.

**Comment by Paul75** [comment] 2019-02-12 16:31
I want to have this screen (result) : https://nimb.ws/T2bVip

Can I do this ?

**Comment by pavvank** [comment] 2019-02-12 16:43
That seems to be a graph
Yes you can make that.

**Comment by Paul75** [comment] 2019-02-12 17:03
Not only also elements

**Comment by pavvank** [comment] 2019-02-12 17:04
Can you connect on someother platform where i can chat, it would be easier

**Comment by Paul75** [comment] 2019-02-12 17:25
Gmail ? Wechat ? WhatsApp ? Facebook ?

**Comment by pavvank** [comment] 2019-02-12 17:26
gmail.
pavvank@gmail.com

**Closed as completed** 2019-02-13 13:37 UTC
